//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClientMDW.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/ChatServiceMDW")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ChatCallbacks", ConfigurationName="ServiceReference1.IChat", CallbackContract=typeof(ChatClientMDW.ServiceReference1.IChatCallback))]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddMessage", ReplyAction="ChatCallbacks/IChat/AddMessageResponse")]
        void AddMessage(string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddMessage", ReplyAction="ChatCallbacks/IChat/AddMessageResponse")]
        System.Threading.Tasks.Task AddMessageAsync(string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/Subscribe", ReplyAction="ChatCallbacks/IChat/SubscribeResponse")]
        bool Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/Subscribe", ReplyAction="ChatCallbacks/IChat/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/UnSubscribe", ReplyAction="ChatCallbacks/IChat/UnSubscribeResponse")]
        bool UnSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/UnSubscribe", ReplyAction="ChatCallbacks/IChat/UnSubscribeResponse")]
        System.Threading.Tasks.Task<bool> UnSubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/GetOnlinePlayers", ReplyAction="ChatCallbacks/IChat/GetOnlinePlayersResponse")]
        ChatClientMDW.ServiceReference1.Player[] GetOnlinePlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/GetOnlinePlayers", ReplyAction="ChatCallbacks/IChat/GetOnlinePlayersResponse")]
        System.Threading.Tasks.Task<ChatClientMDW.ServiceReference1.Player[]> GetOnlinePlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/PrivateSubscribe", ReplyAction="ChatCallbacks/IChat/PrivateSubscribeResponse")]
        bool PrivateSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/PrivateSubscribe", ReplyAction="ChatCallbacks/IChat/PrivateSubscribeResponse")]
        System.Threading.Tasks.Task<bool> PrivateSubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddPrivateMessage", ReplyAction="ChatCallbacks/IChat/AddPrivateMessageResponse")]
        void AddPrivateMessage(string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddPrivateMessage", ReplyAction="ChatCallbacks/IChat/AddPrivateMessageResponse")]
        System.Threading.Tasks.Task AddPrivateMessageAsync(string playerName, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ChatCallbacks/IChat/onMessageAdded")]
        void onMessageAdded(System.DateTime timestamp, string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ChatCallbacks/IChat/OnOnline")]
        void OnOnline(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : ChatClientMDW.ServiceReference1.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.DuplexClientBase<ChatClientMDW.ServiceReference1.IChat>, ChatClientMDW.ServiceReference1.IChat {
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddMessage(string playerName, string message) {
            base.Channel.AddMessage(playerName, message);
        }
        
        public System.Threading.Tasks.Task AddMessageAsync(string playerName, string message) {
            return base.Channel.AddMessageAsync(playerName, message);
        }
        
        public bool Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public bool UnSubscribe() {
            return base.Channel.UnSubscribe();
        }
        
        public System.Threading.Tasks.Task<bool> UnSubscribeAsync() {
            return base.Channel.UnSubscribeAsync();
        }
        
        public ChatClientMDW.ServiceReference1.Player[] GetOnlinePlayers() {
            return base.Channel.GetOnlinePlayers();
        }
        
        public System.Threading.Tasks.Task<ChatClientMDW.ServiceReference1.Player[]> GetOnlinePlayersAsync() {
            return base.Channel.GetOnlinePlayersAsync();
        }
        
        public bool PrivateSubscribe() {
            return base.Channel.PrivateSubscribe();
        }
        
        public System.Threading.Tasks.Task<bool> PrivateSubscribeAsync() {
            return base.Channel.PrivateSubscribeAsync();
        }
        
        public void AddPrivateMessage(string playerName, string message) {
            base.Channel.AddPrivateMessage(playerName, message);
        }
        
        public System.Threading.Tasks.Task AddPrivateMessageAsync(string playerName, string message) {
            return base.Channel.AddPrivateMessageAsync(playerName, message);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LoginContract", ConfigurationName="ServiceReference1.ILogin")]
    public interface ILogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/Login", ReplyAction="LoginContract/ILogin/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/Login", ReplyAction="LoginContract/ILogin/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/Register", ReplyAction="LoginContract/ILogin/RegisterResponse")]
        void Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/Register", ReplyAction="LoginContract/ILogin/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginChannel : ChatClientMDW.ServiceReference1.ILogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<ChatClientMDW.ServiceReference1.ILogin>, ChatClientMDW.ServiceReference1.ILogin {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Register(string username, string password) {
            base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
    }
}
